https://github.com/sudhanshu1322/num

In [2]:
import numpy as np

In [3]:
range(10)

range(0, 10)

In [4]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
list(range(3,10.5))

TypeError: 'float' object cannot be interpreted as an integer

In [6]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(.5, 10)

array([0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5])

In [8]:
np.arange(5, -4, -1)

array([ 5,  4,  3,  2,  1,  0, -1, -2, -3])

In [9]:
np.arange(5, -4, -.5)

array([ 5. ,  4.5,  4. ,  3.5,  3. ,  2.5,  2. ,  1.5,  1. ,  0.5,  0. ,
       -0.5, -1. , -1.5, -2. , -2.5, -3. , -3.5])

In [12]:
list(np.linspace(1, 5, 20))

[1.0,
 1.2105263157894737,
 1.4210526315789473,
 1.631578947368421,
 1.8421052631578947,
 2.052631578947368,
 2.263157894736842,
 2.473684210526316,
 2.6842105263157894,
 2.894736842105263,
 3.1052631578947367,
 3.3157894736842106,
 3.526315789473684,
 3.7368421052631575,
 3.9473684210526314,
 4.157894736842105,
 4.368421052631579,
 4.578947368421052,
 4.789473684210526,
 5.0]

In [13]:
np.logspace(1,50,10)

array([1.00000000e+01, 2.78255940e+06, 7.74263683e+11, 2.15443469e+17,
       5.99484250e+22, 1.66810054e+28, 4.64158883e+33, 1.29154967e+39,
       3.59381366e+44, 1.00000000e+50])

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [17]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
np.zeros((3,5,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [19]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [22]:
np.ones((3,4,2))*5

array([[[5., 5.],
        [5., 5.],
        [5., 5.],
        [5., 5.]],

       [[5., 5.],
        [5., 5.],
        [5., 5.],
        [5., 5.]],

       [[5., 5.],
        [5., 5.],
        [5., 5.],
        [5., 5.]]])

In [25]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [27]:
a = np.eye(4)

In [28]:
a.shape

(4, 4)

In [29]:
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [31]:
a.size

16

In [32]:
a.ndim

2

In [33]:
a1 = np.random.randn(3,4)

In [34]:
a1

array([[ 0.62200697, -0.84979092,  0.61974728, -0.8945897 ],
       [-1.7727531 ,  0.52017195, -0.58012576, -0.26962994],
       [ 0.07952839, -0.63691092, -1.77962559,  0.62912412]])

In [36]:
a1[1][1]

0.5201719499098292

In [50]:
# import pandas as pd
# df = pd.DataFrame(a1)
# df.loc[1:1,[1]]

In [51]:
a1[0:2,0:2]

array([[ 0.62200697, -0.84979092],
       [-1.7727531 ,  0.52017195]])

In [52]:
a1[[0,1],0:2]

array([[ 0.62200697, -0.84979092],
       [-1.7727531 ,  0.52017195]])

In [53]:
a1

array([[ 0.62200697, -0.84979092,  0.61974728, -0.8945897 ],
       [-1.7727531 ,  0.52017195, -0.58012576, -0.26962994],
       [ 0.07952839, -0.63691092, -1.77962559,  0.62912412]])

In [54]:
a1[[1,2],3]

array([-0.26962994,  0.62912412])

In [56]:
m1 = np.random.randint(1, 3, (3,3))

In [58]:
m1

array([[2, 1, 2],
       [2, 1, 2],
       [1, 2, 2]])

In [59]:
m2 = np.random.randint(2, 4, (3, 3))

In [60]:
m2

array([[3, 2, 3],
       [3, 2, 3],
       [2, 3, 3]])

In [61]:
m1*m2

array([[6, 2, 6],
       [6, 2, 6],
       [2, 6, 6]])

In [62]:
m1@m2

array([[13, 12, 15],
       [13, 12, 15],
       [13, 12, 15]])

In [65]:
pow(m1, 4)

array([[16,  1, 16],
       [16,  1, 16],
       [ 1, 16, 16]])

In [66]:
np.sqrt(m1)

array([[1.41421356, 1.        , 1.41421356],
       [1.41421356, 1.        , 1.41421356],
       [1.        , 1.41421356, 1.41421356]])

In [67]:
np.log(m1)

array([[0.69314718, 0.        , 0.69314718],
       [0.69314718, 0.        , 0.69314718],
       [0.        , 0.69314718, 0.69314718]])

In [68]:
np.log10(m1)

array([[0.30103, 0.     , 0.30103],
       [0.30103, 0.     , 0.30103],
       [0.     , 0.30103, 0.30103]])

In [69]:
np.exp(m1)

array([[7.3890561 , 2.71828183, 7.3890561 ],
       [7.3890561 , 2.71828183, 7.3890561 ],
       [2.71828183, 7.3890561 , 7.3890561 ]])

In [70]:
m1**2

array([[4, 1, 4],
       [4, 1, 4],
       [1, 4, 4]])